# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messageSender',
            new_name='sender',
        ),
    ]
